### ISSUE TITLE
support for unicode characters

### ISSUE THREAD

**Issue by sterling-tenn** [Stampede/itunes-navidrome-migration#4]
I'm trying to migrate my iTunes library error and I've noticed this error:

```
(env) C:\Users\sterl\Desktop\itunes-navidrome-migration-master>itunestoND.py

This script will migrate certain data from your ITunes library to your Navidrome database.
Back up all your data in case it doesn't work properly on your setup. NO WARRANTIES. NO PROMISES.
The script will DELETE existing data you have in your Navidrome database so it can start "fresh".

Type PROCEED to continue, or Q to quit: PROCEED
Enter the path to the Navidrome database: C:\Users\sterl\Desktop\itunes-navidrome-migration-master\navidrome.db
Enter the path to the Itunes database: C:\Users\sterl\Desktop\itunes-navidrome-migration-master\Library.xml

Parsing Itunes library. This may take a while.
Traceback (most recent call last):
  File "C:\Users\sterl\Desktop\itunes-navidrome-migration-master\itunestoND.py", line 82, in <module>
    with open(itdb_path, 'r') as f: soup = BeautifulSoup(f, 'lxml-xml')
  File "C:\Users\sterl\Desktop\itunes-navidrome-migration-master\env\lib\site-packages\bs4\__init__.py", line 312, in __init__
    markup = markup.read()
  File "C:\Users\sterl\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 129421: character maps to <undefined>
```

Which seems like the issue can be fixed by adding the ```encoding="utf8"``` flag to the open statement that opens the Library.xml file on line 82, in my case, I have a lot of songs in my library using unicode characters (typically Japanese ones) in a lot of fields, after parsing the Library.xml with the utf8 encoding, the results in the navidrome.db aren't as expected:
![image](https://user-images.githubusercontent.com/56081843/236927180-af2f0902-4472-48c5-b2ea-ed16a4d0cf20.png)

the play count for all of the songs are still 0, and the date added field are all the the same, not the ones indicated in the iTunes library

my guess is that there's some mismatch with the unicode characters in the Library.xml and the navidrome.db but I'm not too sure

these two fields are the most important to me so any help here would be great

**Comment by Stampede** [comment]
Thanks for the comments. I did some quick checking and it seems you're right that unless [you specify UTF-8 encoding](https://codereview.doctor/features/python/best-practice/file-open-read-encoding), you can run into problems such as that in Windows. So it looks like you solved problem # 1. I didn't know about that issue, so I'll update the script for that.

As for the Oriental characters...

The script correlates the songs between the two DBs by comparing their file paths. So it makes sense if the paths are different by virtue of their encoding, then nothing will get written to the Navidrome db because the path is "different."

Itunes uses URL encoding for the filepaths, which need to be decoded to match the format that ND uses. See lines 84 and 118 in the script for where that happens. I have some Spanish songs in my library, but no Japanese ones to test on, so if I were you, I would look at how the `unquote` command operates on such characters.

Example from my own Itunes library with some Spanish characters:
```
>>> unquote('Qu%C3%A9%20Paso_/02%20Viente%20A%C3%B1os.mp3')  #input
'Qué Paso_/02 Viente Años.mp3'   # result
```

So I'd suggest using the unquote command on a troublesome song title, and compare that to how the same title is actually represented in the ND database. [Sqlite Browser](https://sqlitebrowser.org/) is a good program for exploring the ND database. Open a copy of your ND database with that, and look in the "media_file" table's `path` column to see how Navidrome represents the file path.

I don't have a Windows computer or  Japanese titles to easily test this, but if you or someone else can figure it out please let us know, or make a pull request or however this works.

I'm only at an intermediate lever in Python, and this is the only script I've written that other people seem interested in, so this is all sort of new to me!

**Comment by sterling-tenn** [comment]
Coming back to this after a while since I've had time, I realized it was just a mistake on my end with the particular way I had my iTunes music folder organized.
The line `it_root_music_path = unquote(soup.find('key', text='Music Folder').next_sibling.text)` Went to find my iTunes music folder in the `/iTunes/iTunes Music/` subfolder, but I had forgotten I stored my iTunes media in a different folder.

Changing the `it_root_music_path` to the correct one solved this issue for me

**Comment by jordanade** [comment]
Yes I'm getting all sorts of `Error while parsing {song_path}. Navidrome does not acknowledge that file's existence.` errors.
My Apple Music Library is on a Mac, but is copied to my Navidrome server using Syncthing.
```
Error while parsing Mercedes Sosa/30 Años/03 Gracias a la vida.mp3. Navidrome does not acknowledge that file's existence.
Maybe Navidrome doesn't like the extension? Skipping.
```

**Comment by kleer001** [comment]
The `ñ` in your example is the clue. I don't think that file is missing at all.

macOS stores filenames decomposed, so in the XML `Años` is `n` plus a combining
tilde rather than a single `ñ`. If your Navidrome box ended up with the composed
form, the two are the same name to us and different bytes to `LIKE`.

I checked a Mac-exported `Library.xml` with 37,828 tracks in it, and every single
path containing an accented character came out decomposed: 309 of them, not one
composed.

So the suffix match at line 125 can't see a file that is sitting right there. It
would only ever hit your accented paths, which is what you're seeing. Probably
#10 as well.

Worth confirming before anything else: compare the raw bytes of one failing path
in the XML against the same row in `media_file`. If they differ, that's it.

The fix is to normalise both sides before comparing, with
`unicodedata.normalize` on each. That means pulling candidates and comparing them
in Python, since SQLite won't normalise inside a `LIKE`. I haven't run this
against your setup, so treat it as a diagnosis and not a patch.

Separately: any track that genuinely moved folders will miss too. Filename
lookup, then the XML's `Size` to break ties, recovers most.
